.\" Manpage for libi2c
.\" Contact thorsten.johannvorderbrueggen@t-online.de to correct errors or typos.
.TH libi2c 3 "07 May 2015" "0.0.1" "libi2c man page"
.SH NAME
libi2c
\-\- some useful i2c functions
.SH SYNOPSIS
.PP
#include \fI <libi2c.h>\fP 
.PP
tbd ... void some_func(void);
.br
tbd ... void some_more_func(void);
.br
.PP
.SH DESCRIPTION
This functions are part of the  
.BR arm926_sdk
(https://github.com/tjohann/arm926_sdk)
.PP
The functions implement some useful i2c functions
.PP
.SH FILES
.BR libi2c.c 
\- function implementation
.br
.BR libi2c.h 
\- interface header 
.br 
.PP
.SH OPTIONS
None
.PP
.SH BUGS
No known bugs
.PP
.SH "SEE ALSO"
.BR arm926_sdk(3)
.PP
.SH AUTHOR
Thorsten Johannvorderbrueggen 
.br
Email: \fB<thorsten.johannvorderbrueggen@t-online.de> \fP

