.\" Manpage for libarietta
.\" Contact thorsten.johannvorderbrueggen@t-online.de to correct errors or typos.
.TH libarietta 3 "15 Dez 2015" "0.0.1" "libarietta man page"
.SH NAME
libarietta
\-\- some useful functions
.SH SYNOPSIS
.PP
#include \fI <libarietta.h>\fP
.PP
tbd ... void func_a(void);
.br
tbd ... void func_b(void);
.br
.PP
.SH DESCRIPTION
This functions are part of the
.BR LED-Dot-matrix based clock
(https://github.com/tjohann/led_dot_matrix_clock)
.PP
The functions implement some useful functions
.PP
.SH FILES
.BR libarietta.c
\- function implementation
.br
.BR libarietta.h
\- interface header
.br
.PP
.SH OPTIONS
None
.PP
.SH BUGS
No known bugs
.PP
.SH "SEE ALSO"
.BR clock_brokerd(1)
.PP
.BR tempd(1)
.PP
.SH AUTHOR
Thorsten Johannvorderbrueggen
.br
Email: \fB<thorsten.johannvorderbrueggen@t-online.de> \fP

