.\" Manpage for tempd
.\" Contact thorsten.johannvorderbrueggen@t-online.de to correct errors or typos.
.TH tempd 8 "11 Oct 2015" "0.0.1" "tempd man page"
.SH NAME
tempd
\-\- the tempd
.SH SYNOPSIS
.PP
.SH DESCRIPTION
This functions are part of the
.BR arm926_sdk
(https://github.com/tjohann/arm926_sdk)
.PP
The tempd daemon
.PP
.SH FILES
.BR tempd.c
\- function implementation
.br
.BR tempd.h
\- interface header
.br
.PP
.SH OPTIONS
None
.PP
.SH BUGS
No known bugs
.PP
.SH "SEE ALSO"
.BR ...(1)
.PP
.BR librietta(3)
.PP
PP
.BR clock_brokerd(8)
.PP
.SH AUTHOR
Thorsten Johannvorderbrueggen
.br
Email: \fB<thorsten.johannvorderbrueggen@t-online.de> \fP

